# Generated by Django 4.1 on 2022-08-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=30)),
                ('original_url', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
